### ISSUE TITLE
An installer crashed in gdimm_32.dll. Possible memory leak?

### ISSUE THREAD

**Issue by sveinn** [CoolOppo/GDIPP#1]
Hello. I've been using GDIPP for a while, thanks for your work on it. 

I just ran into an issue where an installer crashed and the fault originated from `gdimm_32.dll`. I thought I might try to get to the bottom of this and perhaps contribute a solution. Perhaps you can guide me along?

My theory is that the fault has something to do with the fact that the installer was in the process of extracting an archive containing a very large number of files (80 thousand) and displayed the name and path of each file as it was extracted.  Perhaps rendering such a large amount of filenames exposes a memory leak in GDIPP.

I thought I might test that theory by cloning the project and attempting to reproduce the issue by modifying `gdipp_demo`. It seems that it looks for a `demo.conf` file, but none is included in the project. Can you provide a sample one to speed things along please?

**Comment by CoolOppo** [comment]
This is just an unofficial mirror repo. I didn't make this.
